name: API Pipeline

on:
  push:
    branches: [main]

env:
  APP_NAME: "MyPythonApp"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        env:
          TEST_ENV: "API Testing"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Simulate API call
        run: |
          echo "Deploying $APP_NAME to simulated API"
          curl -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" https://httpbin.org/get
        env:
          DEPLOY_ENV: "Simulated Deployment"