name: Hello World Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4
      - name: Say Hello
        run: echo "Hello, github actions, workflow from ubuntu"